//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TitulosPersonalizados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitulosPersonalizados() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Recursos.TitulosPersonalizados", typeof(TitulosPersonalizados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave no coincide con la que se encuentra registrada en mi sistema, inténtalo nuevamente.
        /// </summary>
        internal static string ClaveNoEncontrada {
            get {
                return ResourceManager.GetString("ClaveNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es un campo requerido..
        /// </summary>
        internal static string ErrorCampoRequerido {
            get {
                return ResourceManager.GetString("ErrorCampoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos {0} son campos requeridos..
        /// </summary>
        internal static string ErrorCamposRequeridos {
            get {
                return ResourceManager.GetString("ErrorCamposRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos {0} deben ser campos únicos..
        /// </summary>
        internal static string ErrorCamposUnicos {
            get {
                return ResourceManager.GetString("ErrorCamposUnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del campo {0} ya existe..
        /// </summary>
        internal static string ErrorCampoUnico {
            get {
                return ResourceManager.GetString("ErrorCampoUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave no es valida.
        /// </summary>
        internal static string ErrorClave {
            get {
                return ResourceManager.GetString("ErrorClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo siento, tengo problemas para comprenderte. Por favor intenta reformular tu pregunta..
        /// </summary>
        internal static string ErrorGenerico {
            get {
                return ResourceManager.GetString("ErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presento un error al intentar insertar {0}..
        /// </summary>
        internal static string ErrorInsertar {
            get {
                return ResourceManager.GetString("ErrorInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excediste el numero de intentos, te recomiendo que verifiques tus datos y vuelvas a intentarlo..
        /// </summary>
        internal static string IntentosExcedidos {
            get {
                return ResourceManager.GetString("IntentosExcedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excediste el número de intentos permitidos.
        /// </summary>
        internal static string IntentosExcedidosGenerico {
            get {
                return ResourceManager.GetString("IntentosExcedidosGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para iniciar sesión es necesario que ademas del usuario ingreses tu clave dinamica..
        /// </summary>
        internal static string NoRestablecer {
            get {
                return ResourceManager.GetString("NoRestablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es una opción valida.
        /// </summary>
        internal static string OpcionInvalida {
            get {
                return ResourceManager.GetString("OpcionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para iniciar necesito que por favor digites tu usuario o tu correo institucional.
        /// </summary>
        internal static string PreguntaUsuario {
            get {
                return ResourceManager.GetString("PreguntaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas restablecer tu clave dinámica?.
        /// </summary>
        internal static string RestablecerClave {
            get {
                return ResourceManager.GetString("RestablecerClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola, soy el Asistente Virtual de Seguros Beta. ¿En que puedo ayudarte?.
        /// </summary>
        internal static string SaludoInicial {
            get {
                return ResourceManager.GetString("SaludoInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola {0}, por favor digita tu clave dinamica.
        /// </summary>
        internal static string SaludoUsuario {
            get {
                return ResourceManager.GetString("SaludoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} {1}. ¿Como puedo ayudarte?.
        /// </summary>
        internal static string SaludoUsuarioLogeado {
            get {
                return ResourceManager.GetString("SaludoUsuarioLogeado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Como es la primera vez que ingresas se generó una clave dinámica la cual fue enviada a tu correo..
        /// </summary>
        internal static string SaludoUsuarioNuevo {
            get {
                return ResourceManager.GetString("SaludoUsuarioNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}, generé una nueva clave dinamica y la envie a tu correo, (mail)  para iniciar por favor digita tu clave dinamica..
        /// </summary>
        internal static string SeRestablecioClave {
            get {
                return ResourceManager.GetString("SeRestablecioClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo siento, pero no puedo encontrar tus datos, por favor inténtalo nuevamente..
        /// </summary>
        internal static string UsuarioNoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNoEncontrado", resourceCulture);
            }
        }
    }
}
